DROP TABLE IF EXISTS highlights;

CREATE TABLE highlights (
  id SERIAL PRIMARY KEY,
  currPage SMALLINT NOT NULL,
  pId SMALLINT NOT NULL,
  pStart SMALLINT NOT NULL,
  pEnd SMALLINT NOT NULL,
  pString VARCHAR(255) NOT NULL
)
